RFC: Add ZeroMQ as a transport layer for xpcc.
roboterclubaachen/xpcc pull request #176
Opened 2016-08-28 21:43 UTC by strongly-typed

I opened this PR for discussion.

There are probably some to many fixes and rebases necessary until this is added to mainline. 

But I still think it's worth to use ZeroMQ at RCA after it was successfully demonstrated to control a robot from the internal JavaGUI by ZeroMQ. This PR should bring this effort forward.

2016-08-28 22:10 UTC, ekiwi commented
> You are right. Now fixed

Thank you.

One last question: Why do we need to support zeromq versions < 4.1.1?
If there is a valid use case that still uses an old zeromq version I am for including it, we just have to make sure to keep the maintenance burden small and one way of doing this is to only support the latest version of a library.

2016-08-28 22:16 UTC, strongly-typed commented
Thank for your feedback!

> Why do we need to support zeromq versions < 4.1.1?

I think that on the RPi mounted on the big bot only libzmqpp3 was available. On OSX (with homebrew) I started to develop with libzmqpp4 right away.

> is to only support the latest version of a library.

New is always better? Hmm :-) 
I think of a project at work where a competent project partner chose zeromq3. I will ask him for his reasons.

2016-08-28 22:29 UTC, ekiwi commented
> New is always better? Hmm :-)

of cause :D, as long as I am not being paid I will only support the most recent version of any open source project that I am involved in, and I think that other developers will feel similarly.


> I think that on the RPi mounted on the big bot only libzmqpp3 was available

OK. This is a very important reason!

2016-08-28 23:17 UTC, salkinium commented
Could you please rebase this? The diff is a bit noisy, especially when reviewing commit by commit.

2016-08-29 10:40 UTC, strongly-typed commented
I will redo all commits and separate zeroMQ stuff from non-zeroMQ stuff.
Rebasing is a bit painful because git does not remember how to solve merge conflicts.

2016-08-29 11:39 UTC, strongly-typed commented
So, some cleanup done. Building the example will probably fail because of #178.

2016-08-29 14:05 UTC, daniel-k commented
>  Rebasing is a bit painful because git does not remember how to solve merge conflicts.

Maybe git `rerere` [1] is your friend.

[1] https://git-scm.com/blog/2010/03/08/rerere.html

2016-08-29 17:56 UTC, strongly-typed commented
[Travis CI is soooo outdated.](http://packages.ubuntu.com/search?keywords=libzmqpp-dev)

2016-08-30 21:24 UTC, strongly-typed commented
Travis CI standard is too old (no libzmqpp), Travis CI trusty beta is buggy [#6541](https://github.com/travis-ci/travis-ci/issues/6541). So no Travis CI yet.

2016-08-30 21:33 UTC, salkinium commented
An alternative is Circle CI, but they also only have 14.04 running 😞.

2016-09-01 02:13 UTC, ekiwi commented
There is a gitlab CI running on the latest Arch Linux at RCA. That should be up to date.
@daniel-k @rleh how difficult would it be to make build results public?

2016-10-02 11:24 UTC, strongly-typed commented
So hopefully this compiles on Travis CI with Trusty.
What about #178 ?

2016-10-02 13:35 UTC, salkinium commented
I'm very sorry, but F1 alternate functions is [funktional kaputt](https://www.youtube.com/watch?v=3LNYfAYE72E) and there is no quickfix for now (See #178). Do you have a board other than a F1 to write the STM32 examples with?

2016-10-02 14:01 UTC, strongly-typed commented
The Blue Pill is so bread board friendly :-O
OK, I will then use an **ARDUINO** *scnr*

2016-10-02 18:44 UTC, salkinium commented
Please allow me to push to this PR, I'd like to rebase and resolve the conflict.

2016-10-02 20:13 UTC, salkinium requested changes
Would it be ok to treat the example like the Blue Pill was never involved? So to apply the F4 Discover change commit as a fixup to the stm32 example?

2016-10-02 20:13 UTC, salkinium commented on examples/zmq/README.md
> + * STM32F103 "Blue Pill" development board
```diff
- * STM32F103 "Blue Pill" development board
+ * STM32F407 Discovery development board
```

2016-10-02 20:13 UTC, salkinium commented on examples/zmq/README.md
> +Flash `1_stm32` on the Blue Pill
```diff
- Flash `1_stm32` on the Blue Pill
+ Flash `1_stm32` on the STM32F407 Discovery
```

2016-10-02 20:13 UTC, salkinium commented on src/xpcc/communication/xpcc/backend/zeromq/connector.hpp
> +	~ZeroMQConnector() {}
Should this not disconnect/unbind the socket?

2016-10-03 13:32 UTC, strongly-typed commented on examples/zmq/README.md
> +Flash `1_stm32` on the Blue Pill
You really want to wipe out all evidence ;)

2016-10-03 13:33 UTC, strongly-typed commented on src/xpcc/communication/xpcc/backend/zeromq/connector.hpp
> +	~ZeroMQConnector() {}
Probably the destructor will take care of it. I added `unsubscribe()` and `close()` where possible.

2016-10-03 18:14 UTC, salkinium approved these changes

2016-10-03 18:37 UTC, salkinium commented
Rebased and merged manually.

2016-10-03 18:37 UTC, closed without merging