[unittest] BoundedDeque: Add single element test
roboterclubaachen/xpcc pull request #218
Opened 2017-03-04 22:36 UTC by tomchy

I want to use single element queue, but it doesn't work. See unit test in this PR.

@daniel-k told me to do so :slightly_smiling_face:

2017-03-04 22:47 UTC, tomchy commented
It seems that changing static assignment of tail fixes this issue (still should be checked):
```c
this->tail = (N == 1 ? 0 : 1);
```

This assignment can be found inside constructor and clear() method.

2017-03-05 01:44 UTC, salkinium commented
Is this PR missing the commit with the fix?

2017-03-05 02:10 UTC, tomchy commented
Yes. I've just pushed a simple fix. Please check :slightly_smiling_face:

2017-03-05 15:07 UTC, salkinium requested changes
Apart from the minor change, this is 👍.

2017-03-05 15:07 UTC, salkinium commented on src/xpcc/container/deque_impl.hpp
> +	head(0), size(0)
I'd like this still in the constructor list, that will likely result in one less constructor call for static instantiations.
```diff
-	head(0), tail(1), size(0)
+	head(0), tail(N == 1 ? 0 : 1), size(0)
```

2017-03-05 16:05 UTC, tomchy commented
Changes applied :slightly_smiling_face:

2017-03-05 16:07 UTC, salkinium approved these changes

2017-03-05 16:43 UTC, daniel-k commented
👍

2017-03-05 17:20 UTC, salkinium commented
I've squashed and rebased your commit for ~yak~ git history shaving purposes.

2017-03-05 18:34 UTC, merged

2017-03-05 18:35 UTC, salkinium commented
Thanks a lot for the fix!