[stm32l4] I2C Driver
roboterclubaachen/xpcc pull request #248
Opened 2017-05-02 22:03 UTC by strongly-typed

Tested in hardware with STM32L476.

2017-05-03 11:12 UTC, salkinium commented on src/xpcc/architecture/platform/driver/i2c/stm32l4/i2c_master.cpp.in
> +				// stream << "nextOperation = " << nextOperation << xpcc::endl;
btw, you can also do:
```cpp
DEBUG_STREAM("nextOperation =" << nextOperation);
```

2017-05-03 11:12 UTC, salkinium commented on src/xpcc/architecture/platform/driver/i2c/stm32l4/i2c_master.cpp.in
> +	}
Duplicate and wrong code.

2017-05-03 11:12 UTC, salkinium commented on src/xpcc/architecture/platform/driver/i2c/stm32l4/i2c_master.cpp.in
> +	return error;
Oh hey, look, we've got our own version of `errno`!1!!

2017-05-03 11:12 UTC, salkinium commented on src/xpcc/architecture/platform/driver/i2c/stm32l4/i2c_master.hpp.in
> +		constexpr uint8_t trise = trise_raw > 62 ? 63 : (trise_raw + 1);
I'm working on the correct timing calculation.

2017-05-05 18:00 UTC, strongly-typed commented on src/xpcc/architecture/platform/driver/i2c/stm32l4/i2c_master.cpp.in
> +				// stream << "nextOperation = " << nextOperation << xpcc::endl;
Thanks. That's much nicer!

2017-05-05 18:01 UTC, strongly-typed commented on src/xpcc/architecture/platform/driver/i2c/stm32l4/i2c_master.cpp.in
> +	}
Uups, from copy-paste ...

2017-05-05 18:01 UTC, strongly-typed commented on src/xpcc/architecture/platform/driver/i2c/stm32l4/i2c_master.cpp.in
> +	return error;
I did not invent it :-)

2017-05-10 20:29 UTC, salkinium commented on src/xpcc/architecture/platform/driver/i2c/stm32l4/i2c_master.hpp.in
> +		constexpr uint8_t trise = trise_raw > 62 ? 63 : (trise_raw + 1);
I've looked at the documentation, and this is a bit more complicated than I can currently spend time on, so I suggest the following to not block this PR: Let's keep this configuration hardcoded for now, and replace these computations with a `static_assert` (and `// FIXME:`) for 100kHz baudrate at 48MHz clock.

2017-05-11 09:17 UTC, strongly-typed commented on src/xpcc/architecture/platform/driver/i2c/stm32l4/i2c_master.hpp.in
> +		constexpr uint8_t trise = trise_raw > 62 ? 63 : (trise_raw + 1);
No problem. A hardcoded LUT would be OK for the beginning. The LUT now has one entry ;-) Just pushed the change.

2017-05-11 09:42 UTC, salkinium approved these changes
Nice!

2017-05-11 10:57 UTC, salkinium requested changes

2017-05-11 10:57 UTC, salkinium commented on src/xpcc/architecture/platform/devices/stm32/stm32l476_486-j_m_q_r_v_z-c_e_g.xml
> +    <driver type="i2c" name="stm32l4" instances="1,2,3"/>
Is this driver also compatible with the other L4 devices? If so, can you also [change the DFG output](https://github.com/roboterclubaachen/xpcc/blob/develop/tools/device_file_generator/dfg/stm32/stm_writer.py#L77), so I don't forget when porting to modm?

2017-05-12 01:55 UTC, strongly-typed commented on src/xpcc/architecture/platform/devices/stm32/stm32l476_486-j_m_q_r_v_z-c_e_g.xml
> +    <driver type="i2c" name="stm32l4" instances="1,2,3"/>
By visually comparing the I2C register map from all STM32L series

| Reference Manual | Series | Compatible |
| ---------- | ---------- |---|
| RM0038 | STM32L100xx, STM32L151xx, STM32L152xx and STM32L162xx | NO |
| RM0351 | STM32L4x5 and STM32L4x6 | YES |
| RM0377 | STM32L0x1 | YES |
| RM0392 | STM32L4x1 | YES |
| RM0393 | STM32L4x2 | YES |
| RM0394 | STM32L43xxx STM32L44xxx STM32L45xxx STM32L46xxx | YES |
| RM0395 | STM32L4x5 | YES |


I found no obvious difference for STM32L0 and STM32L4. So it seems to be a general rule that the L0 and L4 series uses this 'new' I2C IP. So the name stm32l4 might not be optimal.

The STM32L1 series looks like the STM32F4 but missing the FLTR register.

I updated the DFG without testing. @salkinium Could you please update the device files?

2017-05-13 18:36 UTC, strongly-typed commented
Maybe my last comment here got lost ...

I visually compared the reference manuals of all STM32L* processors

| Reference Manual | MCUs | I2C_CR1 PECEN |
|---|---|---|
| RM0038 | STM32L100xx, STM32L151xx, STM32L152xx and STM32L162xx | fehlt |
| RM0351 | STM32L4x5 and STM32L4x6 |   |
| RM0377 | STM32L0x1 |   |
| RM0392 | STM32L4x1 |   |
| RM0393 | STM32L4x2 |   |
| RM0394 | STM32L43xxx STM32L44xxx STM32L45xxx STM32L46xxx |   |
| RM0395 | STM32L4x5 | |

STM32L4 and STM32L0 seem to share the same I2C, but STM32L1 does not.

2017-05-13 22:43 UTC, salkinium commented
> STM32L4 and STM32L0 seem to share the same I2C, but STM32L1 does not.

Yeah, **obviously**. Why simple, when it can be complicated?2??

2017-05-13 22:44 UTC, salkinium approved these changes

2017-05-13 23:20 UTC, merged

2017-05-13 23:21 UTC, salkinium commented
Thanks for the good work!