Driver for DS1302 and some goodies.
roboterclubaachen/xpcc pull request #251
Opened 2017-05-10 22:34 UTC by strongly-typed

2017-05-11 22:51 UTC, salkinium commented
I like your `examples/generic` idea a lot! We can also get rid of a lot of `{board}/blink` examples by adding a way to specify the `build.board` via the command line and building this folder with multiple boards via TravisCI.

Furthermore I'm thinking of exporting the entire folder to `getting-started-with-xpcc` with every release to get good and tested examples. I've been hesitant to have to maintain two repos, if we can automate the manual sync away, the overall experience become much better for everyone.

2017-05-11 23:15 UTC, salkinium requested changes
Documentation of the driver config struct needs some investigation, rest is ok.
Still amused that the real time clock driver has a bus interface that can only be bit banged, lol.

2017-05-11 23:15 UTC, salkinium commented on src/xpcc/architecture/platform/board/nucleo64_arduino.hpp
> +#define XPCC_STM32_NUCLEO_ARDUINO_HPP
```diff
- XPCC_STM32_NUCLEO_ARDUINO_HPP
+ XPCC_STM32_NUCLEO64_ARDUINO_HPP
```

2017-05-11 23:15 UTC, salkinium commented on src/xpcc/architecture/platform/board/nucleo64_arduino.hpp
> +using D15 = GpioB8;
I was hesitant to do such a thing, since there is one Nucleo64 (F334) whose pinout differs in 3 pins. But lets solve it when it becomes an issue.

2017-05-11 23:15 UTC, salkinium commented on src/xpcc/driver/rtc/ds1302/ds1302.hpp
> +		///
yes?

2017-05-11 23:15 UTC, salkinium commented on src/xpcc/driver/rtc/ds1302/ds1302.hpp
> +	using Io   = typename PinSet::Io;
This is a good idea, but I think an inherited base struct would be clearer from a documentation view (see https://github.com/roboterclubaachen/xpcc/pull/86#issuecomment-186578136 for demo).  Also the class should probably be called `Config` for conformance with future drivers using this for more than just pins.

2017-05-11 23:16 UTC, salkinium commented on src/xpcc/architecture/platform/board/nucleo64_arduino.hpp
> +#define XPCC_STM32_NUCLEO_ARDUINO_HPP
Hey, one more project name and I have Bingo! BWAHAHA

2017-05-13 20:01 UTC, strongly-typed commented
I adopted your proposal and changed it to an inherited `Config` class.

2017-05-13 22:52 UTC, salkinium commented
> I adopted your proposal and changed it to an inherited Config class.

Oh, we'll bastardize C++ in The Name of Embedded™ till Stroustrup begs for mercy. BWHAHAHA!

2017-05-13 22:52 UTC, salkinium approved these changes

2017-05-13 23:06 UTC, merged