[io] Check arguments of printf format string
roboterclubaachen/xpcc pull request #263
Opened 2017-07-04 09:03 UTC by Maju-Ketchup

XPCC is missing checking the arguments of printf
When using `XPCC_LOG_INFO.printf("%d", (double)66.0)` a "0"  is written into the log stream w/out compile time warning

https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes

2017-07-04 10:04 UTC, salkinium requested changes
Very nice, such an improvement.

2017-07-04 10:04 UTC, salkinium commented on src/xpcc/io/iostream.hpp
>  	vprintf(const char *fmt, va_list vlist);
Please add it to this function too.

2017-07-05 09:08 UTC, Maju-Ketchup commented on src/xpcc/io/iostream.hpp
>  	vprintf(const char *fmt, va_list vlist);
If I've read the GCC doc correctly you cannot apply the attribute check to vprintf like functions the only thing you can do is checking the string for correctness. 
`For functions where the arguments are not available to be checked (such as vprintf), specify the third parameter as zero. In this case the compiler only checks the format string for consistency.` -gcc documentation
But I assume that this is better than nothing and will add this in a free minute.

2017-07-05 13:18 UTC, Maju-Ketchup commented on src/xpcc/io/iostream.hpp
>  	vprintf(const char *fmt, va_list vlist);
-Done-

2017-07-05 13:26 UTC, salkinium approved these changes
Thanks!

2017-07-05 13:29 UTC, Maju-Ketchup commented
Compiling the Linux example will now throw some Warnings of people who used the printf function wrongly before:
`xpcc/build/linux/printf/libxpcc/generated_platform/driver/core/hosted/assert.cpp:71:78: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘uintptr_t {aka long unsigned int}’ [-Wformat=]
  if (context) { XPCC_LOG_ERROR.printf(" @ %p (%d)", (void *) context, context); }`
and:
`xpcc/src/xpcc/ui/gui/widgets/numberfield.cpp:57:33: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int’ [-Wformat=]
  out->printf("%03ld", afterComma);`

2017-07-05 23:31 UTC, strongly-typed commented
Good spot! There are more warnings of that kind:

* [can_message.cpp](https://travis-ci.org/roboterclubaachen/xpcc/jobs/250345555#L1269)
* And many in [bme280_data_impl_fp.hpp](https://travis-ci.org/roboterclubaachen/xpcc/jobs/250345566#L1241) and related files.

2017-07-06 07:45 UTC, daniel-k commented
> `xpcc/src/xpcc/ui/gui/widgets/numberfield.cpp:57:33: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int’ [-Wformat=] out->printf("%03ld", afterComma);`

Well that was probably me 😄 This &^%& gui code becomes slightly embarassing in retrospect :D

2017-07-06 08:26 UTC, strongly-typed commented
> `can-message.cpp`
> `bme280_data_impl_fp.hpp`

Well, that was probably me 😄 This &^%& test  code becomes slightly embarassing in retrospect :D

2017-07-06 08:34 UTC, salkinium commented
Time to build ~a~ with `-Wall`.

2017-07-08 12:46 UTC, merged