Feature/stm32 peripheral view
roboterclubaachen/xpcc pull request #266
Opened 2017-07-10 17:01 UTC by AndreGilerson

Implemented #264 in coorperation with @strongly-typed. Header parsing based on [this commit](https://github.com/modm-io/modm/commit/45ed70a1ced1d07611960a34b5461ab1e71bffb6#diff-a2fed1aded63972e79d485660e8c7dcaR76) by @salkinium

2017-07-10 17:49 UTC, salkinium requested changes
👍 for using a scons tool for this, very nice.
Please update the parser code with the new commit.

2017-07-10 17:49 UTC, salkinium commented on src/xpcc/architecture/platform/driver/core/cortex/linkerscript/peripherals.ld.in
> +%% endfor
Am I missing something? Why is this file added twice?

2017-07-10 17:49 UTC, salkinium commented on scons/site_tools/stm32_parse_headers.py
> +import re
Add a BSD licence header with your name, my name and Sascha's name if he contributed. I give permission to relicense my contributions to this code as BSD.

2017-07-10 17:49 UTC, salkinium commented on src/xpcc/architecture/platform/devices/peripherals.c.in
> + * This file is part of the modm project.
Replace with xpcc BSD header file. I give permission to relicense this code as BSD.

2017-07-10 17:49 UTC, salkinium commented on src/xpcc/architecture/platform/devices/peripherals.ld.in
> + * This file is part of the modm project.
Replace with xpcc BSD header file. I give permission to relicense this code as BSD.

2017-07-10 17:49 UTC, salkinium commented on scons/site_tools/stm32_parse_headers.py
> +		rest = re.findall(r"#define +(.*?) +\(?(?:\(uint32_t\))?(.*?)U?\)? *?(\n|/)", memmapContent)
Please use the version in [this commit](https://github.com/modm-io/modm/commit/13a00cb27f591cea0ec216259d214e27dac225d8), which deals with some header files having spaces in the cast `(uint32_t )` and cleans up a few other things (also works for Cortex-M core peripherals). Also need to update the templates.

2017-07-10 17:53 UTC, salkinium commented
@AndreGilerson as you've noticed, we are currently working on the next generation of this framework (over at [modm-io](https://github.com/modm-io)), which will be licensed under MPLv2 (see below for why). Since this is a non-trivial change to xpcc, would you be ok with licensing your (current and future) contributions as MPLv2 as well?

> We are relicensing all source code from 3-clause BSD in xpcc to MPLv2 in modm.
> https://www.mozilla.org/en-US/MPL/2.0/  
> https://en.wikipedia.org/wiki/Mozilla_Public_License
> 
> The MPLv2 license is more restrictive than the BSD license, but less restrictive than (L)GPL:
> - it requires copyleft at file level, but derivatives can be released under other licenses (that are compatible with MPL).
> - in contrast to GPL you only have to provide open-source access to the derived code covered under MPL.
> - It contains a patent retaliation clause, similar to that of the Apache license.
>
> We think MPLv2 is a better choice for modm, as it makes it easier for us to keep modm open-source (copyleft), but does _not_ deter programmers, projects or companies to use modm and contribute back like GPL does.

2017-07-10 17:59 UTC, salkinium commented on scons/site_tools/stm32_parse_headers.py
> +		rest = re.findall(r"#define +(.*?) +\(?(?:\(uint32_t\))?(.*?)U?\)? *?(\n|/)", memmapContent)
Also: Nice use of `codecs`, didn't know about that, totally gonna steal that ;-P

2017-07-10 18:03 UTC, salkinium commented
Travis fails with:
```
ld: cannot open linker script file peripherals.ld: No such file or directory
```
The `peripherals.ld isn't being generated, I guess the scons dependency isn't set right?

2017-12-05 15:09 UTC, AndreGilerson commented
@strongly-typed reminded me about this pull request. As propossed by @daniel-k in #264, simply adding a "-g3" to the compiler options solves the problem. I added that to the scons script, and force pushed the new version on the branch in this pull request.

2017-12-06 00:34 UTC, salkinium approved these changes

2017-12-06 01:18 UTC, rleh commented
Why is the `-g3` flag only added for arm targets?

2017-12-06 09:11 UTC, AndreGilerson commented
I personally have only used/tested it with arm targets.

2017-12-18 02:13 UTC, salkinium commented
Closed this manually in b5540e5c7678f16d68427791d5982f84eb62876f, because I couldn't push to your branch.

2017-12-18 02:13 UTC, closed without merging