Feature/driver ltc2984
roboterclubaachen/xpcc pull request #273
Opened 2017-08-07 10:36 UTC by rleh

Driver for [Linear LTC2983 / LTC2984](http://www.linear.com/product/LTC2984) *Multi-Sensor High Accuracy Digital Temperature Measurement System*.

Currently only RTDs (*Resistance Temperature Device*, e.g. Pt100) are supported. Thermocouple, thermistor or temperature diode sensors are not supported.

Tested in hardware with a LTC2984 chip and Pt100.

2017-08-08 21:44 UTC, rleh commented
Also tested in hardware with a LTC2983 chip and (again) Pt100.

![image](https://user-images.githubusercontent.com/2820734/29096022-65aca680-7c93-11e7-8027-4a4089c7c1ea.png)

2017-08-11 10:24 UTC, salkinium requested changes

2017-08-11 10:24 UTC, salkinium commented on examples/stm32f4_discovery/temperature_ltc2984/main.cpp
> +		PT_CALL(tempSensor.setChannels());
Why is it called twice and without `PT_CALL`?

2017-08-11 10:24 UTC, salkinium commented on examples/stm32f4_discovery/temperature_ltc2984/main.cpp
> +			logger << "Time: " << (xpcc::Clock::now() - stamp) << xpcc::endl;
This is really not going to be accurate with printing in between. Then again, it's only 1ms resolution anyways. You could use `xpcc::cortex::CycleCounter::getCount()` to get a much more accurate measurement if you need it.

2017-08-11 10:24 UTC, salkinium commented on src/xpcc/driver/temperature/ltc2984.cpp
> + * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
Please use the short license text as usual.

2017-08-11 10:24 UTC, salkinium commented on src/xpcc/driver/temperature/ltc2984.hpp
> +		};
Why is this not a `xpcc::Register`?

2017-08-11 10:24 UTC, salkinium commented on src/xpcc/driver/temperature/ltc2984.hpp
> + * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
same here, short license pls.

2017-08-11 10:24 UTC, salkinium commented on src/xpcc/driver/temperature/ltc2984.hpp
> +#define XPCC__LTC2984_HPP
Single `_` please.

2017-08-11 10:24 UTC, salkinium commented on src/xpcc/driver/temperature/ltc2984.hpp
> +		enum class TemperatureUnit : uint8_t {
Here and below: put `{` on next line.

2017-08-11 10:24 UTC, salkinium commented on src/xpcc/driver/temperature/ltc2984_impl.hpp
> +#ifndef XPCC__LTC2984_HPP
single `_`

2017-08-11 10:24 UTC, salkinium commented on src/xpcc/driver/temperature/ltc2984_impl.hpp
> +	static uint8_t config = (static_cast<uint8_t>(rejection) | static_cast<uint8_t>(temperatureUnit));
Why can't you use `buffer` here? This adds another byte to the class.

2017-08-11 10:24 UTC, salkinium commented on src/xpcc/driver/temperature/ltc2984_impl.hpp
> +	static CommandStatus status;
same here as above.

2017-08-11 16:40 UTC, rleh commented on examples/stm32f4_discovery/temperature_ltc2984/main.cpp
> +			logger << "Time: " << (xpcc::Clock::now() - stamp) << xpcc::endl;
A conversion takes about 150ms, so 1ms accuracy should be sufficient

2017-08-11 18:12 UTC, salkinium requested changes
Nice driver, just two small changes please.

2017-08-11 18:12 UTC, salkinium commented on src/xpcc/driver/temperature/ltc2984.hpp
> +struct ltc2984 {
🚨 brace police 🚨

2017-08-11 18:12 UTC, salkinium commented on src/xpcc/driver/temperature/ltc2984_impl.hpp
> +#include "ltc2984.hpp"
nope.

2017-08-11 18:50 UTC, rleh commented on src/xpcc/driver/temperature/ltc2984.hpp
> +struct ltc2984 {
Fixed

2017-08-11 18:52 UTC, salkinium submitted a review, later dismissed
👍

2017-08-12 14:53 UTC, salkinium commented
It looks like I can't rebase this on develop myself, so please rebase this branch.

2017-08-12 15:00 UTC, rleh commented
Rebased on develop.

Hmm, *[ ] Allow edits from maintainers.* is not checked, but I don't know why.

2017-08-12 15:14 UTC, merged