[fix][io]fixxed that only low 32Bit of an uint64_t were shown in Logstream
roboterclubaachen/xpcc pull request #315
Opened 2017-11-17 16:59 UTC by Maju-Ketchup

While working with 40+Bit Register I stored into an uint64_t, I wanted to put them via printf into my  debug Logstream.
Problem was only the low 32Bits were shown in the log.

`//Example code`
`uint64_t a = 0xFEDCBA9876543210;`
`XPCC_LOG_DEBUG.printf("%llx",a);`
`// Output is "76543210"`

We (@AndreGilerson and I) fixxed the issue in the iostream.hpp and  iostream_printf.cpp editing the "long" variables to "long long"

2017-11-17 23:22 UTC, salkinium commented
1. Well… that commit message definitely needs to be fixxed 😜
2. Can you please add a unit test for 64-bit integers?
3. The use of 64-bit integers is going to hurt AVR performance quite a bit. Please create a typedef for the `long long`s you replaced and point them to `long` for `XPCC__CPU_AVR`. We'll deal with enabling 64-bit support on AVRs later.

2017-11-20 06:58 UTC, Maju-Ketchup commented
I'm on it.
There are no unittest for the printf function right now. I'll try to implement them.
And yes, I am "**fixing**" the commit massage -.-' (stupid English language with its unpredictable exceptions)

2017-11-20 08:26 UTC, Maju-Ketchup commented
Done.

2017-11-20 21:00 UTC, salkinium submitted a review, later dismissed
Thanks!

2017-11-21 12:23 UTC, strongly-typed commented
@Maju-Ketchup 
Could you please assess memory and performance impacts? Yes, `printf` is a heavy piece of cake and xpcc's `printf` is a (false?) compromise between functionality and size/speed for microcontrollers. It's always unclear how to optimise. As 32 bit is the native data width for Cortex-M, I would focus on that. For that `uint64_t` corner case some other solution might be appropriate.

2017-11-21 13:55 UTC, Maju-Ketchup commented
An other alternative would be an extra function only for long longs this won't hurt the performance of the other types, but this would make it possible to display 64bit values as well.

2017-11-21 14:01 UTC, salkinium commented
What about spitting the 64bit into two 32bit prints?  The logic for this would go into the [printf string parsing function](https://github.com/roboterclubaachen/xpcc/blob/develop/src/xpcc/io/iostream_printf.cpp#L178), not the formatting function. This wouldn't slow down every integer print.

2017-11-21 14:10 UTC, Maju-Ketchup commented
My thougths  - I'll do it tomorrow morning.

2017-11-21 19:56 UTC, ekiwi commented
How about just using [IO Streams](https://github.com/roboterclubaachen/xpcc/blob/develop/src/xpcc/io/iostream.hpp#L305)?
Then you do not have to deal with all the varg function weirdness in C/C++.

2017-11-21 19:57 UTC, ekiwi commented
We could also investigate a more C++ way of implementing `printf`.
Something like: https://github.com/c42f/tinyformat

2017-11-21 20:22 UTC, Maju-Ketchup commented
Using printf has the precious ability to display numbers to a diffrent base (eg 2 or 16) which is pretty awesome while debuging registers. Tiny format looks intresting and I will take a look into it.

2017-11-21 20:27 UTC, chris-durand commented
> We could also investigate a more C++ way of implementing printf.

👍. Variadic templates are a nice way to implement a type safe printf, but you have to keep in mind the code bloat this might cause. For every combination of arguments and in every translation unit the compiler will instantiate the function template. I don't know if this is a practical problem on AVR.

Template functions are a possibility to avoid the overhead of uint64_t operations when printing smaller types. The arithmetic operations could be moved to a template function taking the required int type as a template argument.

2017-11-21 22:01 UTC, ekiwi commented
> Using printf has the precious ability to display numbers to a diffrent base (eg 2 or 16)

https://github.com/roboterclubaachen/xpcc/blob/develop/src/xpcc/io/iostream.hpp#L107
https://github.com/roboterclubaachen/xpcc/blob/develop/src/xpcc/io/iostream.hpp#L115

2017-11-22 16:24 UTC, Maju-Ketchup commented
Made a different function to print those 64bit values.
I just wanted this fixed for now and leaving future changes / ideas to you right now.

2017-12-08 12:00 UTC, strongly-typed requested changes

2017-12-08 12:00 UTC, strongly-typed commented on src/xpcc/io/iostream.hpp
> +#if !defined(XPCC__CPU_AVR)
`if not defined`
Please be consistent to in regards to line 170.

2017-12-08 14:33 UTC, Maju-Ketchup commented
@strongly-typed corrections done.

2017-12-18 18:48 UTC, strongly-typed commented
Merged manually.

2017-12-18 18:48 UTC, closed without merging